POST http://localhost:8080/api/Todo/User/register
content-Type:application/json


{
    "username":"binhhu12@gmail.com",
    "password":"Binhthanh@87"
}

###

POST http://localhost:8080/api/Todo/User/login
content-Type:application/json


{
    "username":"binhhu12@gmail.com",
    "password":"Binhthanh@87"
}


###
POST http://localhost:8080/api/Todo/Post/createPost
content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmMyZjZiYjVhOWJhYjkyMmU2YTczODMiLCJpYXQiOjE2NTY5NDY3ODN9.CiQiF4dOh3rgh_qrRGsc7bj4VC2XK52nvNpBJmN6Loo

   {
     "title":"a5234234242445",
      "description":"Học reacjs nên học các thư viện cần thiết sau: React-routerdom,React-redux,Redux-thunk,Antd,MaterialUI,React-Scroll,React-Player,Axios...",
      "status":"LEARNING",
      "url":"reactjs.org"
    }

###
GET http://localhost:8080/api/Todo/Post 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmMyZjZiYjVhOWJhYjkyMmU2YTczODMiLCJpYXQiOjE2NTY5NDY3ODN9.CiQiF4dOh3rgh_qrRGsc7bj4VC2XK52nvNpBJmN6Loo 


###
PUT http://localhost:8080/api/Todo/Post/updatePost/62c30043db2bfda9e4a0e957
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmMyZjZiYjVhOWJhYjkyMmU2YTczODMiLCJpYXQiOjE2NTY5NDY3ODN9.CiQiF4dOh3rgh_qrRGsc7bj4VC2XK52nvNpBJmN6Loo 

{
  "title":"angulaJS AND pythorn",
      "description":"Học vuejs nên học các thư viện cần thiết sau: React-routerdom,React-redux,Redux-thunk,Antd,MaterialUI,React-Scroll,React-Player,Axios...",
      "status":"LEARNED",
      "url":"reactjs.org"
    
}
### bai tap cua  thay

GET http://localhost:8080/api/Auth
Content-Type: application/json
